apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "17"
  generation: 26
  name: d-PROJECT_NAME
  namespace: n-PROJECT_NAME
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-n-PROJECT_NAME-d-PROJECT_NAME
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        POD_LABEL
        workload.user.cattle.io/workloadselector: apps.deployment-n-PROJECT_NAME-d-PROJECT_NAME
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: env
                operator: In
                values:
                - dev
      serviceAccountName: sa-image-pull-secret
      containers:
      - image: REGISTRY/PROJECT_NAME:TAG
        imagePullPolicy: Always
        name: d-PROJECT_NAME
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: PORT
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: v-localtime
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Ho_Chi_Minh
          type: File
        name: v-localtime
---
apiVersion: v1
kind: Service
metadata:
  name: s-PROJECT_NAME
  namespace: n-PROJECT_NAME
spec:
  ports:
  - name: port-gradle
    port: PORT
    protocol: TCP
    targetPort: PORT
  selector:
    POD_LABEL
  sessionAffinity: None
  type: ClusterIP
---
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/affinity: cookie
      nginx.ingress.kubernetes.io/affinity-mode: persistent
      nginx.ingress.kubernetes.io/proxy-body-size: 100m
      nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
      nginx.ingress.kubernetes.io/session-cookie-hash: sha1
      nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
      nginx.ingress.kubernetes.io/session-cookie-name: ingress-cookie
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    name: i-PROJECT_NAME
    namespace: n-PROJECT_NAME
  spec:
    rules:
    - host: PUBLIC_DOMAIN
      http:
        paths:
        - backend:
            service:
              name: s-PROJECT_NAME
              port:
                number: 8080
          path: /
          pathType: Prefix
    tls:
    - hosts:
      - '*.saigonbpo.vn'
      secretName: cert-PROJECT_NAME
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    cattle.io/creator: norman
  name: pv-PROJECT_NAME
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    path: PV_PATH
    server: 10.1.1.12
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: env
          operator: In
          values:
          - dev
  volumeMode: Filesystem
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-PROJECT_NAME
  namespace: n-PROJECT_NAME
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: pv-PROJECT_NAME
